name: Run Bot
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install selenium
          wget https://chromedriver.storage.googleapis.com/133.0.6943.98/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
      - name: Run bot
        run: python faucetbot.py
